### ISSUE TITLE
Question Retrieval Issues

### ISSUE THREAD

**Issue by Minimistro32** [josh-wassum/Study-Flashcards#34]
# Errors
As I was implemented the activities for quizzes and practice I discovered the following.
## getAllQuizzesWithTopic(str: topic)
When using getAllQuizzesWithTopic, supplying ADDITION or SUBTRACTION yield no results. I couldn't quickly ascertain if values exist in the DB for those topics. 

## getAllFlashCardsWithTopic(str: topic)
When using getAllFlashCardsWithTopic, supplying MULTIPLICATION or DIVISION yield no results (despite values existing in the DB). 

![image](https://user-images.githubusercontent.com/65469567/157286857-014f309c-9927-436d-ba91-2bfc81640134.png)
![image](https://user-images.githubusercontent.com/65469567/157286879-cebed25c-ceda-41e0-b369-4c8b1a19fd90.png)

**Comment by omabney** [comment]
Its failing because for quizzes , there is no questions in the database for ADDITION, SUBTRACTION and for FlashCard, there is no questions for MULTIPLICATION and DIVISION. It's only for testing purpose.

Changes to make:
1. Get quizzes from getAllQuizzesWithTopicNotAttempted() - So user will get all not attempted questions
2. Before starting the quiz check the list is empty - So we can check whether user has attempted the topic or not
3. After finishing each topic in quizzes you can call the function to update the mastery.(For each topic assign 20 points).

If you have any questions please let me know?
